# Generated by Django 2.0.1 on 2018-01-22 08:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название области')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена обслуживания')),
                ('polygon', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название организации')),
                ('mail', models.CharField(max_length=255, verbose_name='Емейл')),
                ('phone', models.CharField(max_length=255, verbose_name='Телефон')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
            ],
        ),
        migrations.AddField(
            model_name='area',
            name='provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='provider.Provider', verbose_name='Поставщик'),
        ),
    ]
